- manorMatch/src/App.jsx
> Change Title

- manorMatch/src/App.jsx
- manorMatch/src/components/CalendarBooking/CalendarBooking.jsx
- manorMatch/src/components/Carousel/Carousel.jsx
- manorMatch/src/components/LandingPage/LandingPage.jsx
- manorMatch/src/components/LiveChat/LiveChat.jsx
- manorMatch/src/components/ShoppingCart/ShoppingCart.jsx
- manorMatch/src/components/UserAuthentication/UserAuth.jsx
- manorMatch/src/components/VendorModal/VendorModal.jsx
Set up components in React for each feature
> Added component folders for each feature

- manorMatch/.exampleenv
- manorMatch/database/db.js
- manorMatch/database/model.js
- manorMatch/server/index.js
Created database directory, server directory
> Initialize database, server

- manorMatch/src/App.jsx
- manorMatch/src/components/HomePage/HomePage.jsx
- manorMatch/src/components/LandingPage/NavBar.jsx
- manorMatch/src/components/UserAuthentication/UserAuth.jsx
Added React Router functionality to app
> Added routes

- manorMatch/database/db.js
- manorMatch/database/model.js
- manorMatch/server/index.js
Refactored require statements to import statements in /db and /server directories
> Refactored database/server code for import syntax

- manorMatch/.gitignore
- manorMatch/src/components/LandingPage/NavBar.jsx
- manorMatch/src/components/LandingPage/Slideshow.jsx
- manorMatch/src/components/LandingPage/Testimonials.jsx
Videos and testimonials on landing page with global styling
> Landingpage

- manorMatch/package-lock.json
- manorMatch/package.json
- manorMatch/src/components/LandingPage/NavBar.jsx
- manorMatch/src/components/LandingPage/Slideshow.jsx
- manorMatch/src/components/LandingPage/Testimonials.jsx
> Landing page

- manorMatch/src/components/LandingPage/ChatStandIn.jsx
- manorMatch/src/components/LandingPage/LandingPage.jsx
- manorMatch/src/components/LandingPage/NavBar.jsx
- manorMatch/src/components/LandingPage/Slideshow.jsx
- manorMatch/src/components/LandingPage/Testimonials.jsx
Bouncing logo behind the loading videos
> Videos now pulling from vimeo

- manorMatch/src/components/ShoppingCart/AddressInputs.jsx
- manorMatch/src/components/ShoppingCart/CartService.jsx
- manorMatch/src/components/ShoppingCart/ShoppingCart.jsx
Add Checkout component in shopping cart and update css style.
Please help review and approve. Thanks a bunch~
> Add Checkout component in shopping cart and update css style

- manorMatch/.exampleenv
- manorMatch/package-lock.json
- manorMatch/package.json
- manorMatch/server/index.js
- manorMatch/src/App.jsx
- manorMatch/src/components/ShoppingCart/CartService.jsx
- manorMatch/src/components/ShoppingCart/Checkout.jsx
- manorMatch/src/components/ShoppingCart/PaymentSuccess.jsx
- manorMatch/src/components/ShoppingCart/ShoppingCart.jsx
Implement Stripe Payment Connected with Shopping Cart Checkout and Add Success Page.
Please review and Approval
> Implement Stripe Payment Connected with Shopping Cart Checkout

- manorMatch/database/models/index.js
- manorMatch/database/models/services.js
- manorMatch/server/controllers/index.js
- manorMatch/server/controllers/services.js
- manorMatch/server/routes/routes.js
- manorMatch/src/components/Carousel/Carousel.jsx
- manorMatch/src/components/Carousel/CarouselImage.jsx
- manorMatch/src/components/Carousel/CarouselModal.jsx
- manorMatch/src/components/Carousel/CarouselTile.jsx
- manorMatch/src/components/HomePage/HomePage.jsx
- Created a server route to get service data from localhost:3000
- Backend data now flows into carousel.
- Moved inaccessible vendor route so its accessible (I let Styles know already).
> Backend Data Flows into carousel. Created backend route. 

- manorMatch/.exampleenv
- manorMatch/server/routes/routes.js
- manorMatch/src/components/Booking/Vendors.jsx
- manorMatch/src/components/HomePage/HomePage.jsx
- manorMatch/src/components/ShoppingCart/ShoppingCart.jsx
Update Example env file and move cartICon to the nav bar.
Please help review. thanks a bunch
> Update Example env file and move cartICon to the nav bar

- manorMatch/src/components/HomePage/HomePage.jsx
- manorMatch/src/components/ShoppingCart/PaymentSuccess.jsx
- manorMatch/src/components/ShoppingCart/ShoppingCart.jsx
Fix the trashIcon( remove services) not working issue
> Fix the remove services issue

- manorMatch/src/components/HomePage/HomePage.jsx
- manorMatch/src/components/ShoppingCart/ShoppingCart.jsx
- manorMatch/src/index.css
- manorMatch/tailwind.config.js
Update the card number and Css style
> Update the card number and Css style

- manorMatch/src/components/Booking/Vendors.jsx
- manorMatch/src/components/UserAuthentication/SignUp.jsx
- manorMatch/src/components/UserAuthentication/UserAuth.jsx
Changed default form fill text color to white
Updated axios.get endpoint for Vendors.jsx
> Updated CSS for login and sign up pages

- manorMatch/src/components/Booking/Vendors.jsx
Fixed axios.get template literal in Vendors.jsx
> Fixed template literal in Vendors.jsx

- manorMatch/src/components/Carousel/CarouselTile.jsx
- manorMatch/src/components/LandingPage/Testimonials.jsx
Typo: For the first commit "Fix carusel", I meant fix Landing page testimonial
> Carousel 2

- manorMatch/server/index.js
Changed CORS headers in server/index.js
> Chat refresh

- manorMatch/server/routes/routes.js
- User can navigate correctly to by typing url/login url/signup without errors 
- Updated routes.js to prevent HTTP request headers if already sent previously
- Set up router so that it server will serve client index.html file, and route via react router
> Updated handling of server requests to various endpoints

- manorMatch/src/components/LandingPage/LandingPage.jsx
- manorMatch/src/components/LandingPage/Testimonials.jsx
- manorMatch/tailwind.config.js
- logo/log in button now floats
- removed nav bar
- updated videos, icons, and height of elements
> update landing page styling

- manorMatch/.exampleenv
- manorMatch/database/seeds.js
> Seedupdate

- manorMatch/src/components/Booking/Confirmation.jsx
- manorMatch/src/components/HomePage/HomePage.jsx
- manorMatch/src/components/ShoppingCart/PaymentSuccess.jsx
- manorMatch/src/components/ShoppingCart/ShoppingCart.jsx
- manorMatch/src/utils/NavBar.jsx
Update NavBar in utils folder with click on M|M logo turn to landing page, add a home button to back to homepage. Please review. thanks a bunch
> Update NavBar in utils folder with click on M|M logo turn to landing page, add a home button to back to homepage

- manorMatch/database/models/user.js
- manorMatch/server/controllers/user.js
- manorMatch/server/routes/routes.js
- manorMatch/src/App.jsx
- manorMatch/src/components/Booking/Booking.jsx
- manorMatch/src/components/Booking/SelectAddress.jsx
- manorMatch/src/components/Carousel/Carousel.jsx
- manorMatch/src/components/Carousel/CarouselImage.jsx
- manorMatch/src/components/Carousel/CarouselTile.jsx
- manorMatch/src/components/HomePage/HomePage.jsx
- manorMatch/src/components/UserProfile/UserProfile.jsx
**Passing user address to 'selected address' dropdown in the "SelectAddress" component.**
- Created address collection in the database.
- Connected front end and back end to grab user address based in email/id. 
**Moved a useEffect into App.jsx to be able to capture current user and their addresses and move to two components.**
> Stored addresses now render in the bookings SelectAddress component. 

- manorMatch/src/App.jsx
- manorMatch/src/components/Carousel/Carousel.jsx
- manorMatch/src/components/Carousel/CarouselImage.jsx
- manorMatch/src/components/Carousel/CarouselTile.jsx
- manorMatch/src/components/HomePage/HomePage.jsx
- manorMatch/src/components/UserAuthentication/SignUp.jsx
- manorMatch/src/components/UserAuthentication/UserAuth.jsx
- manorMatch/src/components/UserProfile/UserProfile.jsx
Split my single useEffects into two separate useEffects. Couldn't grab a user if we didn't have one yet!
I also promisified our result of getting from local storage. When we set to localStorage, NOW we navigate to home after--rather than trying to immediately navigate to home, where we might not have a user yet to give to you!
> Manipulating time - a useEffect, promisified journey

- manorMatch/src/components/LandingPage/LandingPage.jsx
- manorMatch/src/components/LandingPage/Mission.jsx
- manorMatch/src/components/LandingPage/Services.jsx
- manorMatch/src/components/LandingPage/Slideshow.jsx
- manorMatch/src/components/LandingPage/Testimonials.jsx
- manorMatch/tailwind.config.js
- also fixed issue with the unmounting process breaking the testimonial renders
- text shadow on logo 
- add services component
> add mission statement + styling

- manorMatch/src/components/UserAuthentication/SignOut.jsx
> Completed signout function

- manorMatch/src/App.jsx
- manorMatch/src/components/LiveChat/ChatModal.jsx
Changed Concierge button to be shorter and fit vetter
Removed extra button
> Changed name of chat button, removed unneccssary close chat

- manorMatch/src/components/UserProfile/UserProfile.jsx
- manorMatch/src/utils/NavBar.jsx
- manorMatch/src/utils/UserControlls.jsx
remove the home button on the login page. and keep the home button on other pages near M|M logo
Please review. Thanks a bunch
> remove the home button on the login page. and keep the home button on other pages
